from typing import Dict, Any, Optional
import subprocess
import hashlib
from pathlib import Path


def get_spec_commit_hash(spec_path: Optional[str | Path] = None, spec_content: Optional[str] = None) -> str:
    """
    Returns the Git commit hash of the specification file or repo HEAD,
    falling back to a deterministic SHA-256 hash of the spec content.
    """
    if spec_path and Path(spec_path).exists():
        try:
            res = subprocess.run(
                ["git", "log", "-n", "1", "--pretty=format:%h", "--", str(spec_path)],
                capture_output=True,
                text=True,
                check=False
            )
            if res.returncode == 0 and res.stdout.strip():
                return res.stdout.strip()
        except Exception:
            pass

    try:
        res = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=False
        )
        if res.returncode == 0 and res.stdout.strip():
            return res.stdout.strip()
    except Exception:
        pass

    if spec_content:
        return hashlib.sha256(spec_content.encode("utf-8")).hexdigest()[:8]

    return "head-spec"


TERRAFORM_HEADER = """# Generated by SDD-Infra pipeline. DO NOT EDIT DIRECTLY.
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0.2"
    }
  }
}

provider "docker" {}
"""

CONTAINER_TEMPLATE = """
resource "docker_image" "{image_resource_name}" {{
  name         = "{image}"
  keep_locally = true
}}

resource "docker_container" "{container_name}" {{
  name  = "{container_name}"
  image = docker_image.{image_resource_name}.image_id

  labels {{
    label = "owner"
    value = "{owner}"
  }}

  labels {{
    label = "public_access"
    value = "{public_access}"
  }}

  labels {{
    label = "ssh_enabled"
    value = "{ssh_enabled}"
  }}
}}
"""


AWS_TERRAFORM_HEADER = """# Generated by SDD-Infra for AWS ECS Fargate. DO NOT EDIT DIRECTLY.
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      ManagedBy = "SDD-Infra"
    }
  }
}

resource "aws_ecs_cluster" "main" {
  name = "sdd-infra-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}
"""

KUBERNETES_TERRAFORM_HEADER = """# Generated by SDD-Infra for Kubernetes. DO NOT EDIT DIRECTLY.
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.26"
    }
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}

resource "kubernetes_namespace" "app_ns" {
  metadata {
    name = "sdd-infra"
    labels = {
      managed_by = "sdd-infra"
    }
  }
}
"""


def render_docker_terraform(resource_plan: Dict[str, Any], spec_commit: Optional[str] = None) -> str:
    """Renders Terraform HCL for local Docker provider with owner and spec-commit traceability labels."""
    blocks = [TERRAFORM_HEADER]
    images_created = set()

    for resource in resource_plan.get("resources", []):
        base_name = resource["name"]
        image = resource["image"]
        replicas = resource.get("replicas", 1)
        public_access = "true" if resource.get("public_access") else "false"
        ssh_enabled = "true" if resource.get("ssh_enabled") else "false"
        owner = resource.get("tags", {}).get("owner", "unknown")
        commit_tag = spec_commit or resource.get("tags", {}).get("spec_commit") or resource_plan.get("metadata", {}).get("spec_commit") or get_spec_commit_hash()

        image_identifier = base_name.replace("-", "_") + "_img"

        for i in range(1, replicas + 1):
            container_name = f"{base_name}-{i}" if replicas > 1 else base_name
            container_identifier = container_name.replace("-", "_")

            if image_identifier not in images_created:
                image_block = f"""
resource "docker_image" "{image_identifier}" {{
  name         = "{image}"
  keep_locally = true
}}"""
                blocks.append(image_block)
                images_created.add(image_identifier)

            extra_hcl = ""
            if "postgres" in image:
                extra_hcl = """
  env = [
    "POSTGRES_PASSWORD=postgres"
  ]"""
            elif "node" in image or "alpine" in image:
                extra_hcl = """
  command = ["tail", "-f", "/dev/null"]"""

            container_block = f"""
resource "docker_container" "{container_identifier}" {{
  name  = "{container_name}"
  image = docker_image.{image_identifier}.image_id{extra_hcl}

  labels {{
    label = "owner"
    value = "{owner}"
  }}

  labels {{
    label = "spec_commit"
    value = "{commit_tag}"
  }}

  labels {{
    label = "public_access"
    value = "{public_access}"
  }}

  labels {{
    label = "ssh_enabled"
    value = "{ssh_enabled}"
  }}
}}"""
            blocks.append(container_block)

    return "\n".join(blocks).strip() + "\n"


def render_aws_ecs_terraform(resource_plan: Dict[str, Any], spec_commit: Optional[str] = None) -> str:
    """Renders production-grade AWS ECS Fargate Terraform definitions with spec-commit tags."""
    blocks = [AWS_TERRAFORM_HEADER]

    for resource in resource_plan.get("resources", []):
        name = resource["name"]
        ident = name.replace("-", "_")
        image = resource["image"]
        replicas = resource.get("replicas", 1)
        public_access = resource.get("public_access", False)
        ssh_enabled = resource.get("ssh_enabled", False)
        owner = resource.get("tags", {}).get("owner", "unknown")
        commit_tag = spec_commit or resource.get("tags", {}).get("spec_commit") or resource_plan.get("metadata", {}).get("spec_commit") or get_spec_commit_hash()

        ingress_cidr = '["0.0.0.0/0"]' if public_access else '["10.0.0.0/16"]'
        ssh_block = ""
        if ssh_enabled:
            ssh_block = """

  ingress {
    description = "SSH Access"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }"""

        sg_block = f"""
resource "aws_security_group" "{ident}_sg" {{
  name        = "{name}-ecs-sg"
  description = "Security group for {name} ECS Fargate service"

  ingress {{
    description = "Application Ingress"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = {ingress_cidr}
  }}{ssh_block}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Name         = "{name}-sg"
    owner        = "{owner}"
    spec_commit  = "{commit_tag}"
    public_access = "{str(public_access).lower()}"
    ssh_enabled  = "{str(ssh_enabled).lower()}"
  }}
}}"""
        blocks.append(sg_block)

        task_def_block = f"""
resource "aws_ecs_task_definition" "{ident}_task" {{
  family                   = "{name}-task"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([
    {{
      name      = "{name}"
      image     = "{image}"
      essential = true
      portMappings = [
        {{
          containerPort = 80
          hostPort      = 80
        }}
      ]
    }}
  ])

  tags = {{
    owner        = "{owner}"
    spec_commit  = "{commit_tag}"
    public_access = "{str(public_access).lower()}"
    ssh_enabled  = "{str(ssh_enabled).lower()}"
  }}
}}"""
        blocks.append(task_def_block)

        service_block = f"""
resource "aws_ecs_service" "{ident}_svc" {{
  name            = "{name}-service"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.{ident}_task.arn
  desired_count   = {replicas}
  launch_type     = "FARGATE"

  network_configuration {{
    subnets          = ["subnet-0123456789abcdef0", "subnet-0fedcba9876543210"]
    security_groups  = [aws_security_group.{ident}_sg.id]
    assign_public_ip = {str(public_access).lower()}
  }}

  tags = {{
    owner       = "{owner}"
    spec_commit = "{commit_tag}"
  }}
}}"""
        blocks.append(service_block)

    return "\n".join(blocks).strip() + "\n"


def render_kubernetes_terraform(resource_plan: Dict[str, Any], spec_commit: Optional[str] = None) -> str:
    """Renders Kubernetes manifests via Terraform Kubernetes provider with spec-commit labels."""
    blocks = [KUBERNETES_TERRAFORM_HEADER]

    for resource in resource_plan.get("resources", []):
        name = resource["name"]
        ident = name.replace("-", "_")
        image = resource["image"]
        replicas = resource.get("replicas", 1)
        public_access = resource.get("public_access", False)
        ssh_enabled = resource.get("ssh_enabled", False)
        owner = resource.get("tags", {}).get("owner", "unknown")
        commit_tag = spec_commit or resource.get("tags", {}).get("spec_commit") or resource_plan.get("metadata", {}).get("spec_commit") or get_spec_commit_hash()

        deployment_block = f"""
resource "kubernetes_deployment" "{ident}_deployment" {{
  metadata {{
    name      = "{name}"
    namespace = kubernetes_namespace.app_ns.metadata[0].name
    labels = {{
      app          = "{name}"
      owner        = "{owner}"
      spec_commit  = "{commit_tag}"
      public_access = "{str(public_access).lower()}"
      ssh_enabled  = "{str(ssh_enabled).lower()}"
    }}
  }}

  spec {{
    replicas = {replicas}

    selector {{
      match_labels = {{
        app = "{name}"
      }}
    }}

    template {{
      metadata {{
        labels = {{
          app          = "{name}"
          owner        = "{owner}"
          spec_commit  = "{commit_tag}"
          public_access = "{str(public_access).lower()}"
          ssh_enabled  = "{str(ssh_enabled).lower()}"
        }}
      }}

      spec {{
        container {{
          image = "{image}"
          name  = "{name}"

          resources {{
            limits = {{
              cpu    = "0.5"
              memory = "512Mi"
            }}
            requests = {{
              cpu    = "0.1"
              memory = "128Mi"
            }}
          }}
        }}
      }}
    }}
  }}
}}"""
        blocks.append(deployment_block)

        service_type = "LoadBalancer" if public_access else "ClusterIP"
        service_block = f"""
resource "kubernetes_service" "{ident}_service" {{
  metadata {{
    name      = "{name}-svc"
    namespace = kubernetes_namespace.app_ns.metadata[0].name
    labels = {{
      app         = "{name}"
      owner       = "{owner}"
      spec_commit = "{commit_tag}"
    }}
  }}

  spec {{
    selector = {{
      app = "{name}"
    }}

    type = "{service_type}"

    port {{
      port        = 80
      target_port = 80
    }}
  }}
}}"""
        blocks.append(service_block)

    return "\n".join(blocks).strip() + "\n"


def render_terraform(resource_plan: Dict[str, Any], target: str = "docker", spec_commit: Optional[str] = None) -> str:
    """
    Pure deterministic HCL renderer mapping JSON resource plan into valid Terraform code.
    Supports 'docker', 'aws_ecs', and 'kubernetes' targets with spec-commit tagging.
    """
    target = target.lower()
    if target in ("aws", "aws_ecs", "ecs", "fargate"):
        return render_aws_ecs_terraform(resource_plan, spec_commit=spec_commit)
    elif target in ("k8s", "kubernetes"):
        return render_kubernetes_terraform(resource_plan, spec_commit=spec_commit)
    else:
        return render_docker_terraform(resource_plan, spec_commit=spec_commit)



