from typing import Dict, Any

TERRAFORM_HEADER = """# Generated by SDD-Infra pipeline. DO NOT EDIT DIRECTLY.
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0.2"
    }
  }
}

provider "docker" {}
"""

CONTAINER_TEMPLATE = """
resource "docker_image" "{image_resource_name}" {{
  name         = "{image}"
  keep_locally = true
}}

resource "docker_container" "{container_name}" {{
  name  = "{container_name}"
  image = docker_image.{image_resource_name}.image_id

  labels {{
    label = "owner"
    value = "{owner}"
  }}

  labels {{
    label = "public_access"
    value = "{public_access}"
  }}

  labels {{
    label = "ssh_enabled"
    value = "{ssh_enabled}"
  }}
}}
"""


AWS_TERRAFORM_HEADER = """# Generated by SDD-Infra for AWS ECS Fargate. DO NOT EDIT DIRECTLY.
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      ManagedBy = "SDD-Infra"
    }
  }
}

resource "aws_ecs_cluster" "main" {
  name = "sdd-infra-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}
"""

KUBERNETES_TERRAFORM_HEADER = """# Generated by SDD-Infra for Kubernetes. DO NOT EDIT DIRECTLY.
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.26"
    }
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}

resource "kubernetes_namespace" "app_ns" {
  metadata {
    name = "sdd-infra"
    labels = {
      managed_by = "sdd-infra"
    }
  }
}
"""


def render_docker_terraform(resource_plan: Dict[str, Any]) -> str:
    """Renders Terraform HCL for local Docker provider."""
    blocks = [TERRAFORM_HEADER]
    images_created = set()

    for resource in resource_plan.get("resources", []):
        base_name = resource["name"]
        image = resource["image"]
        replicas = resource.get("replicas", 1)
        public_access = "true" if resource.get("public_access") else "false"
        ssh_enabled = "true" if resource.get("ssh_enabled") else "false"
        owner = resource.get("tags", {}).get("owner", "unknown")

        image_identifier = base_name.replace("-", "_") + "_img"

        for i in range(1, replicas + 1):
            container_name = f"{base_name}-{i}" if replicas > 1 else base_name
            container_identifier = container_name.replace("-", "_")

            if image_identifier not in images_created:
                image_block = f"""
resource "docker_image" "{image_identifier}" {{
  name         = "{image}"
  keep_locally = true
}}"""
                blocks.append(image_block)
                images_created.add(image_identifier)

            extra_hcl = ""
            if "postgres" in image:
                extra_hcl = """
  env = [
    "POSTGRES_PASSWORD=postgres"
  ]"""
            elif "node" in image or "alpine" in image:
                extra_hcl = """
  command = ["tail", "-f", "/dev/null"]"""

            container_block = f"""
resource "docker_container" "{container_identifier}" {{
  name  = "{container_name}"
  image = docker_image.{image_identifier}.image_id{extra_hcl}

  labels {{
    label = "owner"
    value = "{owner}"
  }}

  labels {{
    label = "public_access"
    value = "{public_access}"
  }}

  labels {{
    label = "ssh_enabled"
    value = "{ssh_enabled}"
  }}
}}"""
            blocks.append(container_block)

    return "\n".join(blocks).strip() + "\n"


def render_aws_ecs_terraform(resource_plan: Dict[str, Any]) -> str:
    """Renders production-grade AWS ECS Fargate Terraform definitions."""
    blocks = [AWS_TERRAFORM_HEADER]

    for resource in resource_plan.get("resources", []):
        name = resource["name"]
        ident = name.replace("-", "_")
        image = resource["image"]
        replicas = resource.get("replicas", 1)
        public_access = resource.get("public_access", False)
        ssh_enabled = resource.get("ssh_enabled", False)
        owner = resource.get("tags", {}).get("owner", "unknown")

        ingress_cidr = '["0.0.0.0/0"]' if public_access else '["10.0.0.0/16"]'
        ssh_cidr = '["0.0.0.0/0"]' if ssh_enabled else '[]'

        sg_block = f"""
resource "aws_security_group" "{ident}_sg" {{
  name        = "{name}-ecs-sg"
  description = "Security group for {name} ECS Fargate service"

  ingress {{
    description = "Application Ingress"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = {ingress_cidr}
  }}

  ingress {{
    description = "SSH Access"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = {ssh_cidr}
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Name         = "{name}-sg"
    owner        = "{owner}"
    public_access = "{str(public_access).lower()}"
    ssh_enabled  = "{str(ssh_enabled).lower()}"
  }}
}}"""
        blocks.append(sg_block)

        task_def_block = f"""
resource "aws_ecs_task_definition" "{ident}_task" {{
  family                   = "{name}-task"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([
    {{
      name      = "{name}"
      image     = "{image}"
      essential = true
      portMappings = [
        {{
          containerPort = 80
          hostPort      = 80
        }}
      ]
    }}
  ])

  tags = {{
    owner        = "{owner}"
    public_access = "{str(public_access).lower()}"
    ssh_enabled  = "{str(ssh_enabled).lower()}"
  }}
}}"""
        blocks.append(task_def_block)

        service_block = f"""
resource "aws_ecs_service" "{ident}_svc" {{
  name            = "{name}-service"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.{ident}_task.arn
  desired_count   = {replicas}
  launch_type     = "FARGATE"

  network_configuration {{
    subnets          = ["subnet-0123456789abcdef0", "subnet-0fedcba9876543210"]
    security_groups  = [aws_security_group.{ident}_sg.id]
    assign_public_ip = {str(public_access).lower()}
  }}

  tags = {{
    owner = "{owner}"
  }}
}}"""
        blocks.append(service_block)

    return "\n".join(blocks).strip() + "\n"


def render_kubernetes_terraform(resource_plan: Dict[str, Any]) -> str:
    """Renders Kubernetes manifests via Terraform Kubernetes provider."""
    blocks = [KUBERNETES_TERRAFORM_HEADER]

    for resource in resource_plan.get("resources", []):
        name = resource["name"]
        ident = name.replace("-", "_")
        image = resource["image"]
        replicas = resource.get("replicas", 1)
        public_access = resource.get("public_access", False)
        ssh_enabled = resource.get("ssh_enabled", False)
        owner = resource.get("tags", {}).get("owner", "unknown")

        deployment_block = f"""
resource "kubernetes_deployment" "{ident}_deployment" {{
  metadata {{
    name      = "{name}"
    namespace = kubernetes_namespace.app_ns.metadata[0].name
    labels = {{
      app          = "{name}"
      owner        = "{owner}"
      public_access = "{str(public_access).lower()}"
      ssh_enabled  = "{str(ssh_enabled).lower()}"
    }}
  }}

  spec {{
    replicas = {replicas}

    selector {{
      match_labels = {{
        app = "{name}"
      }}
    }}

    template {{
      metadata {{
        labels = {{
          app          = "{name}"
          owner        = "{owner}"
          public_access = "{str(public_access).lower()}"
          ssh_enabled  = "{str(ssh_enabled).lower()}"
        }}
      }}

      spec {{
        container {{
          image = "{image}"
          name  = "{name}"

          resources {{
            limits = {{
              cpu    = "0.5"
              memory = "512Mi"
            }}
            requests = {{
              cpu    = "0.1"
              memory = "128Mi"
            }}
          }}
        }}
      }}
    }}
  }}
}}"""
        blocks.append(deployment_block)

        service_type = "LoadBalancer" if public_access else "ClusterIP"
        service_block = f"""
resource "kubernetes_service" "{ident}_service" {{
  metadata {{
    name      = "{name}-svc"
    namespace = kubernetes_namespace.app_ns.metadata[0].name
    labels = {{
      app   = "{name}"
      owner = "{owner}"
    }}
  }}

  spec {{
    selector = {{
      app = "{name}"
    }}

    type = "{service_type}"

    port {{
      port        = 80
      target_port = 80
    }}
  }}
}}"""
        blocks.append(service_block)

    return "\n".join(blocks).strip() + "\n"


def render_terraform(resource_plan: Dict[str, Any], target: str = "docker") -> str:
    """
    Pure deterministic HCL renderer mapping JSON resource plan into valid Terraform code.
    Supports 'docker', 'aws_ecs', and 'kubernetes' targets.
    """
    target = target.lower()
    if target in ("aws", "aws_ecs", "ecs", "fargate"):
        return render_aws_ecs_terraform(resource_plan)
    elif target in ("k8s", "kubernetes"):
        return render_kubernetes_terraform(resource_plan)
    else:
        return render_docker_terraform(resource_plan)


