from typing import Dict, Any

TERRAFORM_HEADER = """# Generated by SDD-Infra pipeline. DO NOT EDIT DIRECTLY.
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0.2"
    }
  }
}

provider "docker" {}
"""

CONTAINER_TEMPLATE = """
resource "docker_image" "{image_resource_name}" {{
  name         = "{image}"
  keep_locally = true
}}

resource "docker_container" "{container_name}" {{
  name  = "{container_name}"
  image = docker_image.{image_resource_name}.image_id

  labels {{
    label = "owner"
    value = "{owner}"
  }}

  labels {{
    label = "public_access"
    value = "{public_access}"
  }}

  labels {{
    label = "ssh_enabled"
    value = "{ssh_enabled}"
  }}
}}
"""


def render_terraform(resource_plan: Dict[str, Any]) -> str:
    """
    Pure deterministic HCL renderer mapping JSON resource plan into valid Terraform code.
    Performs programmatically verified replica expansion. Zero network calls.
    """
    blocks = [TERRAFORM_HEADER]
    images_created = set()

    for resource in resource_plan.get("resources", []):
        base_name = resource["name"]
        image = resource["image"]
        replicas = resource.get("replicas", 1)
        public_access = "true" if resource.get("public_access") else "false"
        ssh_enabled = "true" if resource.get("ssh_enabled") else "false"
        owner = resource.get("tags", {}).get("owner", "unknown")

        # Sanitize image name for HCL identifier
        image_identifier = base_name.replace("-", "_") + "_img"

        for i in range(1, replicas + 1):
            container_name = f"{base_name}-{i}" if replicas > 1 else base_name
            container_identifier = container_name.replace("-", "_")

            # Avoid duplicate docker_image blocks for multi-replica containers
            if image_identifier not in images_created:
                image_block = f"""
resource "docker_image" "{image_identifier}" {{
  name         = "{image}"
  keep_locally = true
}}"""
                blocks.append(image_block)
                images_created.add(image_identifier)

            # Handle image-specific runtime requirements
            extra_hcl = ""
            if "postgres" in image:
                extra_hcl = """
  env = [
    "POSTGRES_PASSWORD=postgres"
  ]"""
            elif "node" in image or "alpine" in image:
                extra_hcl = """
  command = ["tail", "-f", "/dev/null"]"""

            container_block = f"""
resource "docker_container" "{container_identifier}" {{
  name  = "{container_name}"
  image = docker_image.{image_identifier}.image_id{extra_hcl}

  labels {{
    label = "owner"
    value = "{owner}"
  }}

  labels {{
    label = "public_access"
    value = "{public_access}"
  }}

  labels {{
    label = "ssh_enabled"
    value = "{ssh_enabled}"
  }}
}}"""
            blocks.append(container_block)

    return "\n".join(blocks).strip() + "\n"

